### ISSUE TITLE
release drafter get Resource not accessible by integration 

### ISSUE THREAD

**Issue by olamy** [jetty/.eclipsefdn#19]
we want to use https://github.com/marketplace/actions/release-drafter to automatically generate release note from PRs.
But there is a `Resource not accessible by integration ` error see https://github.com/jetty/jetty.setuid/actions/runs/6681654045

our GH configuration is here https://github.com/jetty/jetty.setuid/blob/master/.github/workflows/release-drafter.yml

thanks

**Comment by netomi** [comment]
As the organization has configured to create tokens with read permissions by default you need to specify in the release drafter workflow what permissions you grant to that action. The release drafter needs that:

```
permissions:
      contents: write
      pull-requests: read
```

**Comment by netomi** [comment]
btw. your current configuration you can find also in the dashboard at https://jetty.github.io/.eclipsefdn/configuration/ :

![image](https://github.com/jetty/.eclipsefdn/assets/1048055/a02bf58c-d2ef-4af1-8929-0fc0372d6f3e)

**Comment by olamy** [comment]
@netomi  good catch. Thanks!
