### ISSUE TITLE
Allow OAuth app access restrictions for `rt-jetty-committers`

### ISSUE THREAD

**Issue by joakime** [jetty/.eclipsefdn#31]
Allow users in `rt-jetty-committers` to use IDEs to access jetty org repos for purposes of PR integration.

If we attempt to set this up, we get ...

> Could not connect to repository [github.com/jetty/jetty.project](http://github.com/jetty/jetty.project) with account [github.com/sbordet](http://github.com/sbordet) Although you appear to have the correct authorization credentials, the `jetty` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/

@netomi I cannot find the appropriate section in the self service for this.
How can we enable this for the `rt-jetty-committers` group?

**Comment by joakime** [comment]
cc @sbordet

**Comment by netomi** [comment]
usually applications that try to access github on behalf of a user using oauth authorization, you can request access that will be visible for an administrator to approve. I did check and I did not see a pending request atm.

What app or service are you using that requires oauth access?

**Comment by sbordet** [comment]
@netomi I asked access to the organization "jetty", you should see it now?

The application is "JetBrains IDE Integration by JetBrains".

**Comment by netomi** [comment]
granted

**Comment by sbordet** [comment]
It's working, thanks!
