### ISSUE TITLE
Enable "Block User" for our organization

### ISSUE THREAD

**Issue by joakime** [jetty/.eclipsefdn#48]
It seems our organization cannot use the "Block User" feature as outlined here 

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization

We need to figure out how to enable this feature.

**Comment by joakime** [comment]
@netomi I don't see a configuration that we can flip to enable this from https://otterdog.eclipse.org/projects/rt.jetty
Is this possible to configure via otterdog?

**Comment by netomi** [comment]
I assigned the project-leads team to be moderators for the organization manually.
According to the documentation, you should be able to block users from contributing if needed.

A quick search did not show an API that we can use to set this via the self-service, but I will already create a corresponding ticket, API changes so that might be possible in the near future.

**Comment by joakime** [comment]
@netomi thanks!

We've been seeing a small but steady rise in spam accounts (just posting a word or two, or commenting their name again, or just a gmail address, etc)
Just want to handle those OBVIOUS spam users.  (I report those accounts to github already)

Just for the record, IMO, blocking annoying / demanding / problematic users is not appropriate.

**Comment by joakime** [comment]
Out of curiosity, is there a permission to allow deletion of review comments?
Seems like we can delete normal comments, but if the user does a "review" and comments that way, it's deemed special and cannot be deleted.

See: https://github.com/jetty/jetty.project/pull/12123

**Comment by netomi** [comment]
I noticed some spammer also lately. In general the spam prevention mechanism in GitHub works pretty amazing and I have seen a presentation about it once. But it seems that the spammers find some ways to circumvent and manually blocking some users seems to be needed indeed.

Regarding deletion of comments, I found this:

https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#deleting-a-comment

Now I tested it with the owner account and in fact I cant delete the comment but can hide it with a reason. You should be able to do the same afaict as you have write access to the repo.

**Comment by netomi** [comment]
so I tried the suggestions from https://stackoverflow.com/questions/73427238/how-to-remove-pr-review-comment
and it seems to be that review comments / submitted reviews can indeed not be deleted.

I tried to use the REST API to delete the review but I got:

```
{
  "message": "Validation Failed",
  "errors": [
    "Can not dismiss a commented pull request review"
  ],
  "documentation_url": "https://docs.github.com/rest/pulls/reviews#dismiss-a-review-for-a-pull-request",
  "status": "422"
}
```

**Comment by joakime** [comment]
@netomi thanks for the effort!

I think we can close this issue now.

**Comment by joakime** [comment]
I can confirm that I have "hide" permission now.
It worked on https://github.com/jetty/jetty.project/pull/12111
